name: Barros Map Core - Prova 1
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  build-e-publicar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Gerar o mapa
        run: |
          chmod +x build-tiles.sh
          ./build-tiles.sh
      - name: Publicar
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Link publicado
        run: echo "PROVA 1 PUBLICADA - https://jeremias121210-stack.github.io/mapa-de-corrida/"
